// 1-everything/AspireEverything.WebReact/src/App.tsx
import FrameworkTable from '@/components/FrameworkTable';

export default function App() {
  return (
    <>
      <div className="container">
        <header className="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
          <a href="/" className="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
            <img src="/react.png" className="me-2" width="40" height="40" alt="React logo" />
            <span className="fs-4">Framework Bakeoff</span>
          </a>
        </header>
      </div>
      <div className="container">
        <FrameworkTable />
      </div>
    </>
  );
}

// 1-everything/AspireEverything.WebVue/src/App.vue
<script setup vapor lang="ts">
import FrameworkTable from '@/components/FrameworkTable.vue';
</script>

<template>
  <div class="container">
    <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
        <img src="/vue.png" class="me-2" width="40" height="40" alt="Vue logo" />
        <span class="fs-4">Framework Bakeoff</span>
      </a>
    </header>
  </div>

  <div class="container">
    <FrameworkTable />
  </div>
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>
